### ISSUE TITLE
Users set to Away, even when online

### ISSUE THREAD

**Issue by okrek6** [krabs-github/com.krabs.discordmemberstatus.sdPlugin#1]
![image](https://user-images.githubusercontent.com/36323683/132105803-bffb368a-2cd1-4df1-a0b1-1a44f7dfa017.png)
Users that are online are showing offline after 10 mins, and stay that way even after lower the refresh interval.

**Comment by krabs-github** [comment]
Try pasting the JSON API URL into a browser windows. This will show you the raw JSON. You should be able to see if it is correct or incorrect. Also, you may hit a rate limit if you have too many requests in a short period.

Unfortunately, Discord statuses via the JSON API sometimes takes from instant to a few minutes. 10 minutes is way too long, so I don't suspect that is the issue in your case.

Please let me know what you see or cut & past the result of the JSON API URL in your browser into this issue.

Just FYI:
A new plugin update has been submitted to Elgato also. Hopefully, they will publish it soon. One of the new features is to see the state of your entire server when you press one of the plugin buttons.

**Comment by okrek6** [comment]
I have pasted in the JSON URL in a browser and I am getting JSON data back. Data is showing current active users, those are away, in DND, as well as all Voice Channels. I am able to see if these people are muted, deafened, ect. so I believe that I have the correct data coming through. 

I have also set the rate limit to 60 seconds since my last comment, with no update since then on the individual users. 

I will say that I also that the Discord Member Count on my Stream Deck XL, and that is working properly on both current active users and those that are in Voice Channels.

**Comment by okrek6** [comment]
If I click on the individual users on the Stream Deck, I do get the widget to populate but no data shows up. Just sits on a Refresh wheel.

**Comment by krabs-github** [comment]
Very odd. Since you are a developer and know what you are doing, can you go to: 

`https://discord.com/widget?id=<PUT YOUR SERVER ID HERE>&theme=dark%22%20width=%22350%22%20height=%22500%22%20allowtransparency=%22true%22%20frameborder=%220%22%20sandbox=%22allow-popups%20allow-popups-to-escape-sandbox%20allow-same-origin%20allow-scripts%22`

Replace <PUT YOUR SERVER ID HERE> with your Discord Server ID and paste it into your browser. Lets see what that shows.

**Comment by krabs-github** [comment]
you can also try exiting the stream deck app by right clicking it in the task tray and selecting "Quit Stream Deck". Then restart it and see if the behavior continues.

**Comment by okrek6** [comment]
Preformed both of your suggestions:

1. I get a loading screen, similar to if I had pressed on a User on the Stream Deck and the Widget pops up in a Web App type window (forgive me if I am not using the correct terminology here). I am only speculating and I haven't quite read all of the code but it seems the JSON data is getting hung up somewhere in the logic. Not to say your Algorithms aren't up to snuff, just brain-storming here! I provided an image of what I am seeing.

![image](https://user-images.githubusercontent.com/36323683/132109206-6deeb9a2-caa0-4ce1-887b-1fb3620dc3bc.png)

2. Resetting the Stream Deck by quitting the app fixes the issue, but only temporary. Eventually, the Users return to an Offline state, not even just Away, rather than continuing to be shown as Online.

**Comment by krabs-github** [comment]
If you are getting a loading screen using the link above also, then this is not an issue with the plugin. The link above is soley Discord itself. It appears you or Discord are having a connectivity issue unrelated to the plugin.

**Comment by okrek6** [comment]
Do you have any advice then on what should be done? I can reach out on discord if need be

**Comment by okrek6** [comment]
I was able to find the root to the problem. I run a VPN in the background for a little security and I guess Discord does not work well with that, at least the widgets in particular. Disabling it allowed everything to work flawlessly. Sorry to trouble you, was willing to help program if needed but I guess it didn't have to come to that !

**Comment by krabs-github** [comment]
I am happy you got it figured out!
